
FROM node:20
WORKDIR /app

# Copia apenas os arquivos de dependências primeiro para cache de build
COPY package*.json ./
RUN npm install

# Copia o restante do código
COPY . .

# Copia o arquivo de ambiente, se existir
COPY .env .env

# Exponha a porta usada pelo seu app (ajuste se necessário)
EXPOSE 4000

# Comando para iniciar o app (ajuste se necessário)
CMD ["node", "bin/www"]
